#!/bin/bash
# Auto-generated by Claude Code — syncs skills/workflows index for Claude context

AGENT_DIR="/Users/ryantanmai/WORKSPACE/.agent"
COMMANDS_DIR="/Users/ryantanmai/WORKSPACE/.claude/commands"
INDEX_FILE="$AGENT_DIR/_index.md"

# ── 1. Sync workflows → .claude/commands/ ──────────────────────────────────
mkdir -p "$COMMANDS_DIR"
for f in "$AGENT_DIR/workflows/"*.md; do
  ln -sf "$f" "$COMMANDS_DIR/$(basename $f)" 2>/dev/null
done

# ── 2. Generate skills + workflows index ───────────────────────────────────
cat > "$INDEX_FILE" << 'HEADER'
# Antigravity Agent Index
> Auto-generated. Do not edit manually.

## Available Skills
HEADER

for skill_dir in "$AGENT_DIR/skills"/*/; do
  skill_file="$skill_dir/SKILL.md"
  [ -f "$skill_file" ] || continue

  name=$(basename "$skill_dir")
  desc=$(awk '/^description:/{found=1; gsub(/^description:[[:space:]]*/,""); gsub(/^"/,""); gsub(/"$/,""); print; exit}
              found && /^[^-]/{print; exit}' "$skill_file" | head -c 120)
  globs=$(grep -m1 "^globs:" "$skill_file" 2>/dev/null | sed 's/globs:[[:space:]]*//' | tr -d '"')

  echo "### \`$name\`" >> "$INDEX_FILE"
  echo "- **Path:** \`.agent/skills/$name/SKILL.md\`" >> "$INDEX_FILE"
  [ -n "$desc" ]  && echo "- **When to use:** $desc" >> "$INDEX_FILE"
  [ -n "$globs" ] && echo "- **Auto-trigger on:** \`$globs\`" >> "$INDEX_FILE"
  echo "" >> "$INDEX_FILE"
done

cat >> "$INDEX_FILE" << 'WORKFLOWS_HEADER'
## Available Workflows
WORKFLOWS_HEADER

for wf in "$AGENT_DIR/workflows/"*.md; do
  [ -f "$wf" ] || continue
  name=$(basename "$wf" .md)
  desc=$(grep -m1 "^description:" "$wf" 2>/dev/null | sed 's/description:[[:space:]]*//' | tr -d '"')
  echo "- \`/$name\` — $desc" >> "$INDEX_FILE"
done

echo "" >> "$INDEX_FILE"
echo "_Last synced: $(date '+%Y-%m-%d %H:%M:%S')_" >> "$INDEX_FILE"
